# Generated by Django 4.2.2 on 2023-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
