# Generated by Django 4.2.2 on 2023-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
