# Generated by Django 4.2.2 on 2023-11-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_edited_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="edited_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
