# Generated by Django 4.2.2 on 2023-11-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="deleted",
        ),
    ]
