# Generated by Django 4.2.5 on 2023-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_category_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
